"""empty message

Revision ID: 5d7e488f6747
Revises: 
Create Date: 2021-06-27 12:30:38.743030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7e488f6747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workouts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'user_id')
    # ### end Alembic commands ###
